import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { TraceDatabase } from "@ai-trace/cache";
import { loadGraph, loadRoutes, loadSymbols } from "@ai-trace/cache";
import type { DbSymbol } from "@ai-trace/cache";

function renderComponentMap(symbols: DbSymbol[]): string {
  const components = symbols.filter((s) => s.type === "component");
  const lines = ["# Component Map", ""];

  for (const component of components) {
    lines.push(`## ${component.name}`, "");
    lines.push("File:", "");
    lines.push(`- ${component.filePath}`, "");

    if (component.props?.length) {
      lines.push("", "Props:", "");
      for (const prop of component.props) {
        lines.push(`- ${prop}`);
      }
    }

    if (component.renders?.length) {
      lines.push("", "Renders:", "");
      for (const render of component.renders) {
        lines.push(`- ${render}`);
      }
    }

    if (component.usesHooks?.length) {
      lines.push("", "Uses hooks:", "");
      for (const hook of component.usesHooks) {
        lines.push(`- ${hook}`);
      }
    }

    lines.push("");
  }

  return lines.join("\n");
}

function renderHookMap(symbols: DbSymbol[]): string {
  const hooks = symbols.filter((s) => s.type === "hook");
  const lines = ["# Hook Map", ""];

  for (const hook of hooks) {
    lines.push(`## ${hook.name}`, "");
    lines.push("File:", "");
    lines.push(`- ${hook.filePath}`, "");

    if (hook.calls?.length) {
      lines.push("", "Calls:", "");
      for (const call of hook.calls) {
        lines.push(`- ${call}`);
      }
    }

    if (hook.usesHooks?.length) {
      lines.push("", "Uses hooks:", "");
      for (const inner of hook.usesHooks) {
        lines.push(`- ${inner}`);
      }
    }

    lines.push("");
  }

  return lines.join("\n");
}

function renderRouteMap(routes: ReturnType<typeof loadRoutes>): string {
  const lines = ["# Route Map", ""];

  for (const route of routes) {
    lines.push(`## ${route.path}`, "");
    if (route.pageFile) {
      lines.push(`- page: ${route.pageFile}`);
    }
    for (const layout of route.layoutFiles) {
      lines.push(`- layout: ${layout}`);
    }
    if (route.loadingFile) {
      lines.push(`- loading: ${route.loadingFile}`);
    }
    if (route.errorFile) {
      lines.push(`- error: ${route.errorFile}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function renderAiContext(
  symbols: DbSymbol[],
  routes: ReturnType<typeof loadRoutes>
): string {
  const components = symbols.filter((s) => s.type === "component");
  const hooks = symbols.filter((s) => s.type === "hook");

  const lines = [
    "# AI Context",
    "",
    "## Project",
    "",
    "This context was generated by ai-trace from local source analysis.",
    "",
    "## Important routes",
    "",
    ...routes.slice(0, 10).map((r) => `- ${r.path}`),
    "",
    "## Main components",
    "",
    ...components.slice(0, 20).map((c) => `- ${c.name} (${c.filePath})`),
    "",
    "## Main hooks",
    "",
    ...hooks.slice(0, 20).map((h) => `- ${h.name} (${h.filePath})`),
    "",
    "## Where to look first",
    "",
    "- `.ai-trace/exports/route-map.md` for route flow",
    "- `.ai-trace/exports/component-map.md` for render tree",
    "- `.ai-trace/exports/hook-map.md` for hook usage",
    "- `.ai-trace/exports/graph.json` for machine-readable graph",
    "",
  ];

  return lines.join("\n");
}

export async function exportContext(
  db: TraceDatabase,
  exportDir: string
): Promise<string[]> {
  await mkdir(exportDir, { recursive: true });

  const symbols = loadSymbols(db);
  const routes = loadRoutes(db);
  const graph = loadGraph(db);

  const outputs: [string, string][] = [
    ["ai-context.md", renderAiContext(symbols, routes)],
    ["component-map.md", renderComponentMap(symbols)],
    ["hook-map.md", renderHookMap(symbols)],
    ["route-map.md", renderRouteMap(routes)],
    ["graph.json", JSON.stringify(graph, null, 2)],
    [
      "symbols.json",
      JSON.stringify(
        {
          symbols: symbols.map((s) => ({
            endLine: s.endLine,
            file: s.filePath,
            id: s.id,
            name: s.name,
            props: s.props,
            renders: s.renders,
            startLine: s.startLine,
            type: s.type,
            usesHooks: s.usesHooks,
          })),
        },
        null,
        2
      ),
    ],
    ["routes.json", JSON.stringify({ routes }, null, 2)],
  ];

  const written: string[] = [];

  for (const [fileName, content] of outputs) {
    const filePath = path.join(exportDir, fileName);
    await writeFile(filePath, `${content}\n`, "utf-8");
    written.push(filePath);
  }

  return written;
}
